# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(502, 320)
        self.preference = QtWidgets.QTabWidget(Form)
        self.preference.setGeometry(QtCore.QRect(10, 0, 471, 261))
        self.preference.setObjectName("preference")
        self.camera_preference = QtWidgets.QWidget()
        self.camera_preference.setObjectName("camera_preference")
        self.layoutWidget = QtWidgets.QWidget(self.camera_preference)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 391, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(13)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.width_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.width_edit.setText("")
        self.width_edit.setObjectName("width_edit")
        self.horizontalLayout.addWidget(self.width_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.height_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.height_edit.setText("")
        self.height_edit.setObjectName("height_edit")
        self.horizontalLayout_2.addWidget(self.height_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.fps_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fps_edit.setText("")
        self.fps_edit.setObjectName("fps_edit")
        self.horizontalLayout_3.addWidget(self.fps_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.threshold_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.threshold_edit.setText("")
        self.threshold_edit.setObjectName("threshold_edit")
        self.horizontalLayout_4.addWidget(self.threshold_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.preference.addTab(self.camera_preference, "")
        self.optim_preference = QtWidgets.QWidget()
        self.optim_preference.setObjectName("optim_preference")
        self.groupBox = QtWidgets.QGroupBox(self.optim_preference)
        self.groupBox.setGeometry(QtCore.QRect(0, 90, 441, 138))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 371, 92))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.w_silhouette_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_silhouette_edit.setObjectName("w_silhouette_edit")
        self.horizontalLayout_6.addWidget(self.w_silhouette_edit)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.w_reprojection_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_reprojection_edit.setObjectName("w_reprojection_edit")
        self.horizontalLayout_9.addWidget(self.w_reprojection_edit)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.w_pointcloud_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_pointcloud_edit.setObjectName("w_pointcloud_edit")
        self.horizontalLayout_7.addWidget(self.w_pointcloud_edit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.w_poseprior_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_poseprior_edit.setObjectName("w_poseprior_edit")
        self.horizontalLayout_10.addWidget(self.w_poseprior_edit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.w_temporalprior_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_temporalprior_edit.setObjectName("w_temporalprior_edit")
        self.horizontalLayout_8.addWidget(self.w_temporalprior_edit)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_25.addWidget(self.label_26)
        self.w_shapeprior_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.w_shapeprior_edit.setObjectName("w_shapeprior_edit")
        self.horizontalLayout_25.addWidget(self.w_shapeprior_edit)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_25)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.layoutWidget2 = QtWidgets.QWidget(self.optim_preference)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 2, 441, 88))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(65, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.stepsize_1_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsize_1_edit.sizePolicy().hasHeightForWidth())
        self.stepsize_1_edit.setSizePolicy(sizePolicy)
        self.stepsize_1_edit.setMinimumSize(QtCore.QSize(66, 0))
        self.stepsize_1_edit.setMaximumSize(QtCore.QSize(66, 16777215))
        self.stepsize_1_edit.setObjectName("stepsize_1_edit")
        self.horizontalLayout_11.addWidget(self.stepsize_1_edit)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(69, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.numiters_1_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numiters_1_edit.sizePolicy().hasHeightForWidth())
        self.numiters_1_edit.setSizePolicy(sizePolicy)
        self.numiters_1_edit.setMinimumSize(QtCore.QSize(57, 0))
        self.numiters_1_edit.setMaximumSize(QtCore.QSize(57, 16777215))
        self.numiters_1_edit.setObjectName("numiters_1_edit")
        self.horizontalLayout_11.addWidget(self.numiters_1_edit)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(70, 0))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.est_method = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_method.sizePolicy().hasHeightForWidth())
        self.est_method.setSizePolicy(sizePolicy)
        self.est_method.setMinimumSize(QtCore.QSize(0, 0))
        self.est_method.setMaximumSize(QtCore.QSize(38, 16777215))
        self.est_method.setMaxCount(9)
        self.est_method.setObjectName("est_method")
        self.est_method.addItem("")
        self.est_method.addItem("")
        self.horizontalLayout_11.addWidget(self.est_method, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(65, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.stepsize_2_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsize_2_edit.sizePolicy().hasHeightForWidth())
        self.stepsize_2_edit.setSizePolicy(sizePolicy)
        self.stepsize_2_edit.setMinimumSize(QtCore.QSize(65, 0))
        self.stepsize_2_edit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.stepsize_2_edit.setObjectName("stepsize_2_edit")
        self.horizontalLayout_12.addWidget(self.stepsize_2_edit)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(69, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.numiters_2_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numiters_2_edit.sizePolicy().hasHeightForWidth())
        self.numiters_2_edit.setSizePolicy(sizePolicy)
        self.numiters_2_edit.setMinimumSize(QtCore.QSize(57, 0))
        self.numiters_2_edit.setMaximumSize(QtCore.QSize(57, 16777215))
        self.numiters_2_edit.setObjectName("numiters_2_edit")
        self.horizontalLayout_12.addWidget(self.numiters_2_edit)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(71, 0))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.method = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.method.sizePolicy().hasHeightForWidth())
        self.method.setSizePolicy(sizePolicy)
        self.method.setMinimumSize(QtCore.QSize(0, 0))
        self.method.setMaximumSize(QtCore.QSize(38, 16777215))
        self.method.setMaxCount(9)
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.horizontalLayout_12.addWidget(self.method, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.all_pose = QtWidgets.QCheckBox(self.layoutWidget2)
        self.all_pose.setText("")
        self.all_pose.setObjectName("all_pose")
        self.horizontalLayout_24.addWidget(self.all_pose)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_23.addWidget(self.label_24)
        self.use_prior = QtWidgets.QCheckBox(self.layoutWidget2)
        self.use_prior.setText("")
        self.use_prior.setObjectName("use_prior")
        self.horizontalLayout_23.addWidget(self.use_prior)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.optim_threshold_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.optim_threshold_edit.setObjectName("optim_threshold_edit")
        self.horizontalLayout_13.addWidget(self.optim_threshold_edit)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.preference.addTab(self.optim_preference, "")
        self.monitor_preference = QtWidgets.QWidget()
        self.monitor_preference.setObjectName("monitor_preference")
        self.groupBox_2 = QtWidgets.QGroupBox(self.monitor_preference)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 441, 221))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 423, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.complete_box = QtWidgets.QComboBox(self.widget)
        self.complete_box.setObjectName("complete_box")
        self.complete_box.addItem("")
        self.complete_box.addItem("")
        self.horizontalLayout_15.addWidget(self.complete_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.vis_box = QtWidgets.QComboBox(self.widget)
        self.vis_box.setObjectName("vis_box")
        self.vis_box.addItem("")
        self.vis_box.addItem("")
        self.horizontalLayout_5.addWidget(self.vis_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        self.wrist_pitch_edit = QtWidgets.QLineEdit(self.widget)
        self.wrist_pitch_edit.setObjectName("wrist_pitch_edit")
        self.horizontalLayout_22.addWidget(self.wrist_pitch_edit)
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_22.addWidget(self.label_28)
        self.wrist_yaw_edit = QtWidgets.QLineEdit(self.widget)
        self.wrist_yaw_edit.setObjectName("wrist_yaw_edit")
        self.horizontalLayout_22.addWidget(self.wrist_yaw_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_16.addWidget(self.label_29)
        self.match_threshold_edit = QtWidgets.QLineEdit(self.widget)
        self.match_threshold_edit.setObjectName("match_threshold_edit")
        self.horizontalLayout_16.addWidget(self.match_threshold_edit)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.check_fps_edit = QtWidgets.QLineEdit(self.widget)
        self.check_fps_edit.setObjectName("check_fps_edit")
        self.horizontalLayout_16.addWidget(self.check_fps_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.preference.addTab(self.monitor_preference, "")
        self.path_preference = QtWidgets.QWidget()
        self.path_preference.setObjectName("path_preference")
        self.groupBox_3 = QtWidgets.QGroupBox(self.path_preference)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 371, 211))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 40, 361, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lefthand_edit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lefthand_edit.setObjectName("lefthand_edit")
        self.horizontalLayout_17.addWidget(self.lefthand_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.righthand_edit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.righthand_edit.setObjectName("righthand_edit")
        self.horizontalLayout_18.addWidget(self.righthand_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.detector_edit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.detector_edit.setObjectName("detector_edit")
        self.horizontalLayout_19.addWidget(self.detector_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.pose_edit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.pose_edit.setObjectName("pose_edit")
        self.horizontalLayout_20.addWidget(self.pose_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.preference.addTab(self.path_preference, "")
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 270, 471, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_21.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.apply_button = QtWidgets.QPushButton(self.layoutWidget4)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_21.addWidget(self.apply_button)
        self.cancel_button = QtWidgets.QPushButton(self.layoutWidget4)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_21.addWidget(self.cancel_button)
        self.confirm_button = QtWidgets.QPushButton(self.layoutWidget4)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_21.addWidget(self.confirm_button)

        self.retranslateUi(Form)
        self.preference.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Width"))
        self.label_2.setText(_translate("Form", "Height"))
        self.label_3.setText(_translate("Form", "FPS"))
        self.label_4.setText(_translate("Form", "Threshold"))
        self.preference.setTabText(self.preference.indexOf(self.camera_preference), _translate("Form", "Camera"))
        self.groupBox.setTitle(_translate("Form", "Weights"))
        self.label_9.setText(_translate("Form", "Silhouette"))
        self.label_13.setText(_translate("Form", "Reprojection"))
        self.label_10.setText(_translate("Form", "Pointcloud"))
        self.label_11.setText(_translate("Form", "PosePrior"))
        self.label_12.setText(_translate("Form", "TemporalPrior"))
        self.label_26.setText(_translate("Form", "ShapePrior"))
        self.label_5.setText(_translate("Form", "Stepsize_1"))
        self.label_7.setText(_translate("Form", "Numiters_1"))
        self.label_25.setText(_translate("Form", "Method_est"))
        self.est_method.setItemText(0, _translate("Form", "０"))
        self.est_method.setItemText(1, _translate("Form", "１"))
        self.label_6.setText(_translate("Form", "Stepsize_2"))
        self.label_22.setText(_translate("Form", "Numiters_2"))
        self.label_27.setText(_translate("Form", "Method_opt"))
        self.method.setItemText(0, _translate("Form", "１"))
        self.method.setItemText(1, _translate("Form", "０"))
        self.label_21.setText(_translate("Form", "All_pose"))
        self.label_24.setText(_translate("Form", "Use_Prior"))
        self.label_8.setText(_translate("Form", "Threshold"))
        self.preference.setTabText(self.preference.indexOf(self.optim_preference), _translate("Form", "Optimization"))
        self.label_14.setText(_translate("Form", "手势完成度计算"))
        self.complete_box.setItemText(0, _translate("Form", "基于健侧手势"))
        self.complete_box.setItemText(1, _translate("Form", "基于标准手势"))
        self.label_20.setText(_translate("Form", "可视化"))
        self.vis_box.setItemText(0, _translate("Form", "open3d"))
        self.vis_box.setItemText(1, _translate("Form", "mayavi"))
        self.label_23.setText(_translate("Form", "腕部标准pitch"))
        self.label_28.setText(_translate("Form", "腕部标准yaw"))
        self.label_29.setText(_translate("Form", "异常阈值"))
        self.label_15.setText(_translate("Form", "异常检查频率"))
        self.preference.setTabText(self.preference.indexOf(self.monitor_preference), _translate("Form", "monitor"))
        self.label_16.setText(_translate("Form", "左手模型"))
        self.label_17.setText(_translate("Form", "右手模型"))
        self.label_18.setText(_translate("Form", "检测模型"))
        self.label_19.setText(_translate("Form", "姿态模型"))
        self.preference.setTabText(self.preference.indexOf(self.path_preference), _translate("Form", "Path"))
        self.apply_button.setText(_translate("Form", "应用"))
        self.cancel_button.setText(_translate("Form", "取消"))
        self.confirm_button.setText(_translate("Form", "确认"))

