# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 553)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.display = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setMinimumSize(QtCore.QSize(640, 480))
        self.display.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 16pt \"黑体\";\n"
"color: rgb(255, 0, 0);")
        self.display.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.display.setObjectName("display")
        self.horizontalLayout_15.addWidget(self.display)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(71, 20))
        self.label.setMaximumSize(QtCore.QSize(71, 20))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.ElectrodeState = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElectrodeState.sizePolicy().hasHeightForWidth())
        self.ElectrodeState.setSizePolicy(sizePolicy)
        self.ElectrodeState.setMinimumSize(QtCore.QSize(100, 20))
        self.ElectrodeState.setMaximumSize(QtCore.QSize(100, 20))
        self.ElectrodeState.setAlignment(QtCore.Qt.AlignCenter)
        self.ElectrodeState.setObjectName("ElectrodeState")
        self.horizontalLayout_10.addWidget(self.ElectrodeState)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(71, 20))
        self.label_2.setMaximumSize(QtCore.QSize(71, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.state = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state.sizePolicy().hasHeightForWidth())
        self.state.setSizePolicy(sizePolicy)
        self.state.setMinimumSize(QtCore.QSize(71, 20))
        self.state.setMaximumSize(QtCore.QSize(71, 20))
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.horizontalLayout_11.addWidget(self.state)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(195, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(195, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 30, 171, 288))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(54, 23))
        self.label_3.setMaximumSize(QtCore.QSize(54, 23))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.increase_channel_1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_1.sizePolicy().hasHeightForWidth())
        self.increase_channel_1.setSizePolicy(sizePolicy)
        self.increase_channel_1.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_1.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_1.setObjectName("increase_channel_1")
        self.horizontalLayout.addWidget(self.increase_channel_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.reduce_channel_1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_1.sizePolicy().hasHeightForWidth())
        self.reduce_channel_1.setSizePolicy(sizePolicy)
        self.reduce_channel_1.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_1.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_1.setObjectName("reduce_channel_1")
        self.horizontalLayout.addWidget(self.reduce_channel_1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.electricity_1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_1.sizePolicy().hasHeightForWidth())
        self.electricity_1.setSizePolicy(sizePolicy)
        self.electricity_1.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_1.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_1.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_1.setObjectName("electricity_1")
        self.horizontalLayout.addWidget(self.electricity_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(54, 23))
        self.label_4.setMaximumSize(QtCore.QSize(54, 23))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.increase_channel_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_2.sizePolicy().hasHeightForWidth())
        self.increase_channel_2.setSizePolicy(sizePolicy)
        self.increase_channel_2.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_2.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_2.setObjectName("increase_channel_2")
        self.horizontalLayout_2.addWidget(self.increase_channel_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.reduce_channel_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_2.sizePolicy().hasHeightForWidth())
        self.reduce_channel_2.setSizePolicy(sizePolicy)
        self.reduce_channel_2.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_2.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_2.setObjectName("reduce_channel_2")
        self.horizontalLayout_2.addWidget(self.reduce_channel_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.electricity_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_2.sizePolicy().hasHeightForWidth())
        self.electricity_2.setSizePolicy(sizePolicy)
        self.electricity_2.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_2.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_2.setObjectName("electricity_2")
        self.horizontalLayout_2.addWidget(self.electricity_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(54, 23))
        self.label_5.setMaximumSize(QtCore.QSize(54, 23))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.increase_channel_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_3.sizePolicy().hasHeightForWidth())
        self.increase_channel_3.setSizePolicy(sizePolicy)
        self.increase_channel_3.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_3.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_3.setObjectName("increase_channel_3")
        self.horizontalLayout_3.addWidget(self.increase_channel_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.reduce_channel_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_3.sizePolicy().hasHeightForWidth())
        self.reduce_channel_3.setSizePolicy(sizePolicy)
        self.reduce_channel_3.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_3.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_3.setObjectName("reduce_channel_3")
        self.horizontalLayout_3.addWidget(self.reduce_channel_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.electricity_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_3.sizePolicy().hasHeightForWidth())
        self.electricity_3.setSizePolicy(sizePolicy)
        self.electricity_3.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_3.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_3.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_3.setObjectName("electricity_3")
        self.horizontalLayout_3.addWidget(self.electricity_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(54, 23))
        self.label_6.setMaximumSize(QtCore.QSize(54, 23))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.increase_channel_4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_4.sizePolicy().hasHeightForWidth())
        self.increase_channel_4.setSizePolicy(sizePolicy)
        self.increase_channel_4.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_4.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_4.setObjectName("increase_channel_4")
        self.horizontalLayout_4.addWidget(self.increase_channel_4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.reduce_channel_4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_4.sizePolicy().hasHeightForWidth())
        self.reduce_channel_4.setSizePolicy(sizePolicy)
        self.reduce_channel_4.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_4.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_4.setObjectName("reduce_channel_4")
        self.horizontalLayout_4.addWidget(self.reduce_channel_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.electricity_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_4.sizePolicy().hasHeightForWidth())
        self.electricity_4.setSizePolicy(sizePolicy)
        self.electricity_4.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_4.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_4.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_4.setObjectName("electricity_4")
        self.horizontalLayout_4.addWidget(self.electricity_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(54, 23))
        self.label_7.setMaximumSize(QtCore.QSize(54, 23))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.increase_channel_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_5.sizePolicy().hasHeightForWidth())
        self.increase_channel_5.setSizePolicy(sizePolicy)
        self.increase_channel_5.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_5.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_5.setObjectName("increase_channel_5")
        self.horizontalLayout_5.addWidget(self.increase_channel_5)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.reduce_channel_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_5.sizePolicy().hasHeightForWidth())
        self.reduce_channel_5.setSizePolicy(sizePolicy)
        self.reduce_channel_5.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_5.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_5.setObjectName("reduce_channel_5")
        self.horizontalLayout_5.addWidget(self.reduce_channel_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.electricity_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_5.sizePolicy().hasHeightForWidth())
        self.electricity_5.setSizePolicy(sizePolicy)
        self.electricity_5.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_5.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_5.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_5.setObjectName("electricity_5")
        self.horizontalLayout_5.addWidget(self.electricity_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(54, 23))
        self.label_8.setMaximumSize(QtCore.QSize(54, 23))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.increase_channel_6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_6.sizePolicy().hasHeightForWidth())
        self.increase_channel_6.setSizePolicy(sizePolicy)
        self.increase_channel_6.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_6.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_6.setObjectName("increase_channel_6")
        self.horizontalLayout_6.addWidget(self.increase_channel_6)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.reduce_channel_6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_6.sizePolicy().hasHeightForWidth())
        self.reduce_channel_6.setSizePolicy(sizePolicy)
        self.reduce_channel_6.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_6.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_6.setObjectName("reduce_channel_6")
        self.horizontalLayout_6.addWidget(self.reduce_channel_6)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.electricity_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_6.sizePolicy().hasHeightForWidth())
        self.electricity_6.setSizePolicy(sizePolicy)
        self.electricity_6.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_6.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_6.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_6.setObjectName("electricity_6")
        self.horizontalLayout_6.addWidget(self.electricity_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(54, 23))
        self.label_9.setMaximumSize(QtCore.QSize(54, 23))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.increase_channel_7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_7.sizePolicy().hasHeightForWidth())
        self.increase_channel_7.setSizePolicy(sizePolicy)
        self.increase_channel_7.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_7.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_7.setObjectName("increase_channel_7")
        self.horizontalLayout_7.addWidget(self.increase_channel_7)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.reduce_channel_7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_7.sizePolicy().hasHeightForWidth())
        self.reduce_channel_7.setSizePolicy(sizePolicy)
        self.reduce_channel_7.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_7.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_7.setObjectName("reduce_channel_7")
        self.horizontalLayout_7.addWidget(self.reduce_channel_7)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.electricity_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_7.sizePolicy().hasHeightForWidth())
        self.electricity_7.setSizePolicy(sizePolicy)
        self.electricity_7.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_7.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_7.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_7.setObjectName("electricity_7")
        self.horizontalLayout_7.addWidget(self.electricity_7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(54, 23))
        self.label_10.setMaximumSize(QtCore.QSize(54, 23))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.increase_channel_8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increase_channel_8.sizePolicy().hasHeightForWidth())
        self.increase_channel_8.setSizePolicy(sizePolicy)
        self.increase_channel_8.setMinimumSize(QtCore.QSize(21, 0))
        self.increase_channel_8.setMaximumSize(QtCore.QSize(21, 16777215))
        self.increase_channel_8.setObjectName("increase_channel_8")
        self.horizontalLayout_8.addWidget(self.increase_channel_8)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.reduce_channel_8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_channel_8.sizePolicy().hasHeightForWidth())
        self.reduce_channel_8.setSizePolicy(sizePolicy)
        self.reduce_channel_8.setMinimumSize(QtCore.QSize(21, 0))
        self.reduce_channel_8.setMaximumSize(QtCore.QSize(21, 16777215))
        self.reduce_channel_8.setObjectName("reduce_channel_8")
        self.horizontalLayout_8.addWidget(self.reduce_channel_8)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.electricity_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electricity_8.sizePolicy().hasHeightForWidth())
        self.electricity_8.setSizePolicy(sizePolicy)
        self.electricity_8.setMinimumSize(QtCore.QSize(21, 23))
        self.electricity_8.setMaximumSize(QtCore.QSize(21, 23))
        self.electricity_8.setAlignment(QtCore.Qt.AlignCenter)
        self.electricity_8.setObjectName("electricity_8")
        self.horizontalLayout_8.addWidget(self.electricity_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem26)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem27)
        self.StopEmergency = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopEmergency.sizePolicy().hasHeightForWidth())
        self.StopEmergency.setSizePolicy(sizePolicy)
        self.StopEmergency.setMinimumSize(QtCore.QSize(75, 30))
        self.StopEmergency.setMaximumSize(QtCore.QSize(75, 30))
        self.StopEmergency.setObjectName("StopEmergency")
        self.horizontalLayout_9.addWidget(self.StopEmergency)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_3.raise_()
        self.increase_channel_1.raise_()
        self.reduce_channel_1.raise_()
        self.electricity_1.raise_()
        self.StopEmergency.raise_()
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(67, 0))
        self.label_11.setMaximumSize(QtCore.QSize(67, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.goodside_angle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.goodside_angle.setFont(font)
        self.goodside_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.goodside_angle.setObjectName("goodside_angle")
        self.horizontalLayout_12.addWidget(self.goodside_angle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(67, 0))
        self.label_12.setMaximumSize(QtCore.QSize(67, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.sickside_angle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sickside_angle.setFont(font)
        self.sickside_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.sickside_angle.setObjectName("sickside_angle")
        self.horizontalLayout_13.addWidget(self.sickside_angle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
        self.groupBox.raise_()
        self.label_11.raise_()
        self.goodside_angle.raise_()
        self.display.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 23))
        self.menubar.setObjectName("menubar")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuUsers = QtWidgets.QMenu(self.menubar)
        self.menuUsers.setObjectName("menuUsers")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        self.menu_singlecam = QtWidgets.QMenu(self.menuFunctions)
        self.menu_singlecam.setObjectName("menu_singlecam")
        self.menuGestures = QtWidgets.QMenu(self.menubar)
        self.menuGestures.setObjectName("menuGestures")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_on = QtWidgets.QAction(MainWindow)
        self.action_on.setObjectName("action_on")
        self.action_off = QtWidgets.QAction(MainWindow)
        self.action_off.setObjectName("action_off")
        self.login = QtWidgets.QAction(MainWindow)
        self.login.setObjectName("login")
        self.registration = QtWidgets.QAction(MainWindow)
        self.registration.setObjectName("registration")
        self.action_fist = QtWidgets.QAction(MainWindow)
        self.action_fist.setObjectName("action_fist")
        self.action_wristforward = QtWidgets.QAction(MainWindow)
        self.action_wristforward.setObjectName("action_wristforward")
        self.action_wristbackward = QtWidgets.QAction(MainWindow)
        self.action_wristbackward.setObjectName("action_wristbackward")
        self.action_wristside = QtWidgets.QAction(MainWindow)
        self.action_wristside.setObjectName("action_wristside")
        self.help_doc = QtWidgets.QAction(MainWindow)
        self.help_doc.setObjectName("help_doc")
        self.action_preference = QtWidgets.QAction(MainWindow)
        self.action_preference.setObjectName("action_preference")
        self.action_singlecam_start = QtWidgets.QAction(MainWindow)
        self.action_singlecam_start.setObjectName("action_singlecam_start")
        self.action_singlecam_terminate = QtWidgets.QAction(MainWindow)
        self.action_singlecam_terminate.setObjectName("action_singlecam_terminate")
        self.export_usersdata = QtWidgets.QAction(MainWindow)
        self.export_usersdata.setObjectName("export_usersdata")
        self.menuDevice.addAction(self.action_on)
        self.menuDevice.addAction(self.action_off)
        self.menuUsers.addAction(self.login)
        self.menuUsers.addAction(self.registration)
        self.menuUsers.addAction(self.export_usersdata)
        self.menu_singlecam.addAction(self.action_singlecam_start)
        self.menu_singlecam.addAction(self.action_singlecam_terminate)
        self.menuFunctions.addAction(self.menu_singlecam.menuAction())
        self.menuGestures.addAction(self.action_fist)
        self.menuGestures.addAction(self.action_wristforward)
        self.menuGestures.addAction(self.action_wristbackward)
        self.menuGestures.addAction(self.action_wristside)
        self.menuHelp.addAction(self.help_doc)
        self.menuSettings.addAction(self.action_preference)
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuUsers.menuAction())
        self.menubar.addAction(self.menuFunctions.menuAction())
        self.menubar.addAction(self.menuGestures.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.action_fist.setCheckable(True)
        self.action_wristforward.setCheckable(True)
        self.action_wristbackward.setCheckable(True)
        self.action_wristside.setCheckable(True)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # connect
        self.action_fist.triggered.connect(self.on_fist_triggered)
        self.action_wristforward.triggered.connect(self.on_wristforward_triggered)
        self.action_wristbackward.triggered.connect(self.on_wristbackward_triggered)
        self.action_wristside.triggered.connect(self.on_wristside_triggered)
        self.gesture = ""

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display.setText(_translate("MainWindow", "准备"))
        self.label.setText(_translate("MainWindow", "电极线状态"))
        self.ElectrodeState.setText(_translate("MainWindow", "ElectrodeState"))
        self.label_2.setText(_translate("MainWindow", "连接状态"))
        self.state.setText(_translate("MainWindow", "0"))
        self.groupBox.setTitle(_translate("MainWindow", "电流控制"))
        self.label_3.setText(_translate("MainWindow", "Channel 1"))
        self.increase_channel_1.setText(_translate("MainWindow", "+"))
        self.reduce_channel_1.setText(_translate("MainWindow", "-"))
        self.electricity_1.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Channel 2"))
        self.increase_channel_2.setText(_translate("MainWindow", "+"))
        self.reduce_channel_2.setText(_translate("MainWindow", "-"))
        self.electricity_2.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Channel 3"))
        self.increase_channel_3.setText(_translate("MainWindow", "+"))
        self.reduce_channel_3.setText(_translate("MainWindow", "-"))
        self.electricity_3.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Channel 4"))
        self.increase_channel_4.setText(_translate("MainWindow", "+"))
        self.reduce_channel_4.setText(_translate("MainWindow", "-"))
        self.electricity_4.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Channel 5"))
        self.increase_channel_5.setText(_translate("MainWindow", "+"))
        self.reduce_channel_5.setText(_translate("MainWindow", "-"))
        self.electricity_5.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Channel 6 "))
        self.increase_channel_6.setText(_translate("MainWindow", "+"))
        self.reduce_channel_6.setText(_translate("MainWindow", "-"))
        self.electricity_6.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Channel 7"))
        self.increase_channel_7.setText(_translate("MainWindow", "+"))
        self.reduce_channel_7.setText(_translate("MainWindow", "-"))
        self.electricity_7.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Channel 8"))
        self.increase_channel_8.setText(_translate("MainWindow", "+"))
        self.reduce_channel_8.setText(_translate("MainWindow", "-"))
        self.electricity_8.setText(_translate("MainWindow", "0"))
        self.StopEmergency.setText(_translate("MainWindow", "紧急停止"))
        self.label_11.setText(_translate("MainWindow", "健侧"))
        self.goodside_angle.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "患侧"))
        self.sickside_angle.setText(_translate("MainWindow", "0"))
        self.menuDevice.setTitle(_translate("MainWindow", "设备"))
        self.menuUsers.setTitle(_translate("MainWindow", "用户"))
        self.menuFunctions.setTitle(_translate("MainWindow", "功能"))
        self.menu_singlecam.setTitle(_translate("MainWindow", "单相机监控"))
        self.menuGestures.setTitle(_translate("MainWindow", "手势"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menuSettings.setTitle(_translate("MainWindow", "设置"))
        self.action.setText(_translate("MainWindow", "打开"))
        self.action_on.setText(_translate("MainWindow", "开启"))
        self.action_off.setText(_translate("MainWindow", "关闭"))
        self.login.setText(_translate("MainWindow", "登陆"))
        self.registration.setText(_translate("MainWindow", "注册"))
        self.action_fist.setText(_translate("MainWindow", "握拳"))
        self.action_wristforward.setText(_translate("MainWindow", "腕前屈"))
        self.action_wristbackward.setText(_translate("MainWindow", "腕背伸"))
        self.action_wristside.setText(_translate("MainWindow", "尺桡偏"))
        self.help_doc.setText(_translate("MainWindow", "使用帮助"))
        self.action_preference.setText(_translate("MainWindow", "偏好设置"))
        self.action_singlecam_start.setText(_translate("MainWindow", "开始"))
        self.action_singlecam_terminate.setText(_translate("MainWindow", "终止"))
        self.export_usersdata.setText(_translate("MainWindow", "导出"))

    def on_fist_triggered(self):
        self.action_fist.setChecked(True)
        self.action_wristforward.setChecked(False)
        self.action_wristbackward.setChecked(False)
        self.action_wristside.setChecked(False)
        self.gesture = "fist"

    def on_wristforward_triggered(self):
        self.action_fist.setChecked(False)
        self.action_wristforward.setChecked(True)
        self.action_wristbackward.setChecked(False)
        self.action_wristside.setChecked(False)
        self.gesture = "wristforward"

    def on_wristbackward_triggered(self):
        self.action_fist.setChecked(False)
        self.action_wristforward.setChecked(False)
        self.action_wristbackward.setChecked(True)
        self.action_wristside.setChecked(False)
        self.gesture = "wristforward"

    def on_wristside_triggered(self):
        self.action_fist.setChecked(False)
        self.action_wristforward.setChecked(False)
        self.action_wristbackward.setChecked(False)
        self.action_wristside.setChecked(True)
        self.gesture = "wristside"


import system_rc
import darkstyle.style_rc
